[package]
  name = "peer_chat"
  version = "0.0.16"
  authors = ["willem <willemolding@gmail.com>, Philip Beadle <philip.beadle@holo.host>"]
  edition = "2018"
[dependencies]
  serde = "=1.0.89"
  serde_json = { version = "=1.0.39", features = ["preserve_order"] }
  serde_derive = "=1.0.89"
  derive_more = "0.9.0"
  utils = { path ="../../../utils" }
  validator = "0.9.0"
  validator_derive = "0.9.0"

  hdk = "0.0.38-alpha9"
  hdk_proc_macros = "0.0.38-alpha9"
  holochain_json_derive = "0.0.17"

[lib]
  path = "src/lib.rs"
  crate-type = ["cdylib"]
