# -----------  Agents  -----------
[[agents]]
  id = "test_agent1"
  name = "Agent 1"
  public_address = "HcScjTnefoi6c79eunbqfFNYEYovwaygbPkWEk95xVPd7vemvoB9Qwbjxf458ii"
  keystore_file = "./agent1.keystore"

# -----------  DNAs  -----------

[[dnas]]
  id = "basic_chat_dna"
  file = "./dna/basic-chat.dna.json"
  hash = "QmXWUEQwuoG7TqNBMy6GZT9eP83BsY25juLm1zqzmGgHVw"


# -----------  Instances  -----------

[[instances]]
  id = "basic-chat"
  dna = "basic_chat_dna"
  agent = "test_agent1"
[instances.storage]
  type = "memory"

# -----------  Interfaces  -----------

[[interfaces]]
  id = "websocket_interface"
  admin = true
[interfaces.driver]
  type = "websocket"
  port = 3401
[[interfaces.instances]]
  id = "basic-chat"
# -----------  Networking  -----------

[network]
  type = "sim2h"
  sim2h_url = 'wss://sim2h.holochain.org:9000'