[package]
  name = "utils"
version = "0.0.15"
  authors = ["Philip Beadle <philip.beadle@holo.host>"]

[dependencies]
  serde = "=1.0.89"
  serde_json = { version = "=1.0.39", features = ["preserve_order"] }
  serde_derive = "=1.0.89"
  hdk = "0.0.38-alpha9"
  holochain_json_derive = "0.0.17"
